# -----------------------------
# BUILD STAGE
# -----------------------------
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install --production

COPY . .

# -----------------------------
# RUNTIME STAGE
# -----------------------------
FROM node:18-alpine

WORKDIR /app

# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Copy application files
COPY --from=builder /app /app

# Set correct ownership
RUN chown -R appuser:appgroup /app

# Switch to non-root user
USER appuser

EXPOSE 8080

ENV NODE_ENV=production

CMD ["node","server.js"]