# -------------------------
# BUILD STAGE
# -------------------------

FROM maven:3.9.6-eclipse-temurin-17 AS builder

WORKDIR /build

COPY pom.xml .
COPY src ./src

RUN mvn -B -q clean package -DskipTests

# -------------------------
# RUNTIME STAGE
# -------------------------

FROM gcr.io/distroless/java17-debian11

WORKDIR /app

COPY --from=builder /build/target/*.jar app.jar

USER nonroot

EXPOSE 8080

ENV JAVA_OPTS="-Xms512m -Xmx1024m"

ENTRYPOINT ["java","-jar","/app/app.jar"]